{% raw %}
##
# Db creation
##
---
    - name: install mysql-server
      become: true
      become_method: sudo
      apt: name=default-mysql-server state=present

    - name: Make sure pymysql is present
      become: true
      become_method: sudo
      pip:
        name: pymysql
        state: present

    - name: start db service
      become: true
      become_method: sudo
      service:
        name: mysql
        state: started

    - name: create database
      become: true
      become_method: sudo
      mysql_db:
        name: "{{ db_name }}"
        encoding: utf8
        login_unix_socket: /var/run/mysqld/mysqld.sock
      notify: restart db service
{% endraw %}
