version: '{{cookiecutter.docker_compose_file_version}}'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: {{cookiecutter.project_name}}
      MYSQL_USER: {{cookiecutter.mysql_user}}
      MYSQL_PASSWORD: {{cookiecutter.mysql_user_password}}
      MYSQL_ROOT_PASSWORD: {{cookiecutter.mysql_root_password}}
  web:
    build: .
    working_dir: /app
    command: bash -c "python3 manage.py wait_for_database && python3 manage.py runserver 0:8000"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
