version: '{{cookiecutter.docker_compose_file_version}}'
services:

  {% if cookiecutter.db_backend == "mysql" %}

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: {{cookiecutter.project_name}}
      MYSQL_USER: {{cookiecutter.db_user}}
      MYSQL_PASSWORD: {{cookiecutter.db_user_password}}
      MYSQL_ROOT_PASSWORD: {{cookiecutter.db_root_password}}

  {% elif cookiecutter.db_backend == "postgresql" %}

  db:
    image: postgres
    environment:
      POSTGRES_DB: {{cookiecutter.project_name}}
      POSTGRES_USER: {{cookiecutter.db_user}}
      POSTGRES_PASSWORD: {{cookiecutter.db_root_password}}

  {% endif %}

  web:
    build: .
    working_dir: /app
    command: bash -c "python3 manage.py wait_for_database && python3 manage.py runserver 0:8000"
    volumes:
      - type: bind
        source: ./app
        target: /app
    ports:
      - target: 8000
        published: 8000
    depends_on:
      - db
